<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\WithoutMiddleware;
//use Database\Factories\NationalityFactory;
use App\Models\Nationality;
use Illuminate\Http\Request;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

class NationalityTest extends TestCase
{
    use RefreshDatabase;
    use WithoutMiddleware;
    private $nationality;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->nationality = factory(Nationality::class)->create();
    }
    
    public function testIndex()
    {
        // // Création Mock
        // $this->mock(Nationality::class,function ($mock) 
        // {
        //     $mock->shouldReceive('all')->andReturn('nationalities');
        // });

        //Action
        $response = $this->get(route('nationalities.index'));

        //Assertions
        $response->assertOk();
        $response->assertViewHas('nationalities');
    }

    public function testCreate()
    {
        //Action
        $response = $this->get(route('nationalities.create'));

        //Assertions
        $response->assertOk();
        $response->assertViewIs('nationalities.create');
    }

    public function testStore()
    {
        
        $data = [
            'name' => 'test name create'
        ];

        //Action
        $response = $this->postJson(route('nationalities.store'), $data);

        //Assertions
        $response->assertRedirect(route('nationalities.index'));
        $this->assertDatabaseHas('nationalities', $data);

    }

    public function testEdit()
    {
        // // Création Mock
        // $this->mock(Nationality::class,function ($mock) 
        // {
        //     $mock->shouldReceive('findOrFail')->andReturn('nationality');
        // });

        //Action
        $response = $this->get(route('nationalities.edit', ['id' => $this->nationality->id]));

        //Assertions
        $response->assertOk();
        $response->assertViewHas('nationality');
        $response->assertViewIs('nationalities.edit');
    }

    public function testUpdate()
    {
        $data = [
            'id' => $this->nationality->id,
            'name' => 'test name update'
        ];

        //Action
        $response = $this->postJson(route('nationalities.update',['id' => $this->nationality->id]),$data);
        
        //Assertions
        $response->assertRedirect(route('nationalities.index'));
        $this->assertDatabaseHas('nationalities', $data);
    }

    public function testShow()
    {
        // // Création Mock
        // $this->mock(Nationality::class,function ($mock) 
        // {
        //     $mock->shouldReceive('findOrFail')->andReturn('nationality');
        // });


        //Action
        $response = $this->get(route('nationalities.show', ['id' => $this->nationality->id]));

        //Assertions
        $response->assertSuccessful();
        $response->assertViewHas('nationality');
        $response->assertViewIs('nationalities.show');
    }

    public function testDestroy()
    {
        $data = [
            'id' => $this->nationality->id,
            'name' => $this->nationality->name
        ];

        //Action
        $response = $this->postJson(route('nationalities.delete',['id' => $this->nationality->id]), $data);

        //Assertions
        $response->assertRedirect(route('nationalities.index'));
        $this->assertDatabaseMissing('nationalities',$data);
    }
}
