<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\WithoutMiddleware;
//use Database\Factories\UserFactory;
use App\Models\User;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

class UserTest extends TestCase
{
    use RefreshDatabase;
    use WithoutMiddleware;
    private $role;
    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->role = factory(Role::class)->create();
        $this->user = factory(User::class)->create();
    }
    
    public function testIndex()
    {
        // // Création Mock
        // $this->mock(User::class,function ($mock) 
        // {
        //     $mock->shouldReceive('all')->andReturn('users');
        // });

        //Action
        $response = $this->get(route('users.index'));

        //Assertions
        $response->assertOk();
        $response->assertViewHas('users');
    }

    public function testCreate()
    {
        //Action
        $response = $this->get(route('users.create'));

        //Assertions
        $response->assertOk();
        $response->assertViewIs('users.create');
    }

    public function testStore()
    {
        
        $data = [
            'role_id' => $this->role->id
        ];

        //Action
        $response = $this->postJson(route('users.store'), $data);

        //Assertions
        $response->assertRedirect(route('users.index'));
        $this->assertDatabaseHas('users', $data);

    }

    public function testEdit()
    {
        // // Création Mock
        // $this->mock(User::class,function ($mock) 
        // {
        //     $mock->shouldReceive('findOrFail')->andReturn('user');
        // });

        //Action
        $response = $this->get(route('users.edit', ['id' => $this->user->id]));

        //Assertions
        $response->assertOk();
        $response->assertViewHas('user');
        $response->assertViewIs('users.edit');
    }

    public function testUpdate()
    {
        $data = [
            'id' => $this->user->id,
            'role_id' => $this->role->id
        ];

        //Action
        $response = $this->postJson(route('users.update',['id' => $this->user->id]),$data);
        
        //Assertions
        $response->assertRedirect(route('users.index'));
        $this->assertDatabaseHas('users', $data);
    }

    public function testShow()
    {
        // // Création Mock
        // $this->mock(User::class,function ($mock) 
        // {
        //     $mock->shouldReceive('findOrFail')->andReturn('user');
        // });

        //Action
        $response = $this->get(route('users.show', ['id' => $this->user->id]));

        //Assertions
        $response->assertSuccessful();
        $response->assertViewHas('user');
        $response->assertViewIs('users.show');
    }

    public function testDestroy()
    {
        $data = [
            'id' => $this->user->id,
            'role_id' => $this->role->id
        ];

        //Action
        $response = $this->postJson(route('users.delete',['id' => $this->user->id]), $data);

        //Assertions
        $response->assertRedirect(route('users.index'));
        $this->assertDatabaseMissing('users',$data);
    }
}
